version: '3.1'

services:

  api:
    image: oven/bun
    ports:
    - 3000:3000
    volumes:
    - ./:/home/bun/app
    command: bun --hot run src/server.ts

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9hZzJUHMt7wEjrK3Ujmv

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 9hZzJUHMt7wEjrK3Ujmv
      ME_CONFIG_MONGODB_URL: mongodb://root:9hZzJUHMt7wEjrK3Ujmv@mongo:27017/
